pipeline {
    agent any
	tools {
	maven 'Default'
	jdk 'Default'
	}
	
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample-docker/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build ./java-tomcat-sample-docker -t rishabhchd19/tomcatsample:${env.BUILD_ID}"
            }
        }
		
		stage('Login Dockerhub') {
		    environment {
                DOCKER_CRED = credentials('rishabhchd19-dockerhub')
            }
			steps {
			sh 'echo $DOCKER_CRED_PSW | docker login --username $DOCKER_CRED_USR --password-stdin'
			}
		}
		
		stage('Push Image to Dockerhub') {
			steps {
        sh "docker push rishabhchd19/tomcatsample:${env.BUILD_ID}"
			}
		}
	}
	
	post {
		always {
		sh 'docker logout'
		}
	}
 }